-- DropIndex: remove old single-column unique on Chat.courseId
DROP INDEX IF EXISTS "Chat_courseId_key";

-- AlterTable: drop the @unique from courseId (it had a default constraint generated by Prisma)
-- (the column itself stays, only the unique index changes)

-- DropIndex: remove old Enrollment unique
DROP INDEX "Enrollment_courseId_userId_key";

-- DropIndex: remove old Star unique
DROP INDEX "Star_courseId_userId_key";

-- CreateIndex: composite unique for Chat
CREATE UNIQUE INDEX "Chat_courseId_courseType_key" ON "Chat"("courseId", "courseType");

-- CreateIndex: composite unique for Enrollment
CREATE UNIQUE INDEX "Enrollment_courseId_courseType_userId_key" ON "Enrollment"("courseId", "courseType", "userId");

-- CreateIndex: composite unique for Star
CREATE UNIQUE INDEX "Star_courseId_userId_courseType_key" ON "Star"("courseId", "userId", "courseType");
