import { GlobalConfig } from 'payload';
import { AdminPanelDashboardGroups } from '@/payload-cms/admin-panel-dashboard-groups';
import { MinimalMainContentFieldUnlocalized } from '@/payload-cms/shared-fields/minimal-main-content-field';
import { localizedDefaultValue } from '@/payload-cms/utils/localized-default-value';
import { asLocalizedGlobal } from '@/payload-cms/utils/localized-global';

export const DataPrivacyStatementGlobal: GlobalConfig = asLocalizedGlobal({
  slug: 'data-privacy-statement',
  label: {
    en: 'Data Privacy Statement',
    de: 'Datenschutzerklärung',
    fr: 'Déclaration de confidentialité',
  },

  fields: [
    {
      type: 'tabs',
      tabs: [
        {
          name: 'content',
          label: {
            en: 'Content',
            de: 'Seiteninhalt',
            fr: 'Contenu',
          },
          fields: [
            {
              name: 'pageTitle',
              label: {
                en: 'Page Title',
                de: 'Seitentitel',
                fr: 'Titre de la page',
              },
              type: 'text',
              required: true,
              localized: true,
              defaultValue: localizedDefaultValue({
                de: 'Datenschutzerklärung',
                en: 'Data Privacy Statement',
                fr: 'Déclaration de confidentialité',
              }),
              admin: {
                readOnly: true,
                description: {
                  en: 'This is the title that will be displayed on the page.',
                  de: 'Dies ist der Titel, der auf der Seite angezeigt wird.',
                  fr: "C'est le titre qui sera affiché sur la page.",
                },
              },
            },

            MinimalMainContentFieldUnlocalized,
          ],
        },
        {
          name: 'seo',
          label: {
            en: 'SEO',
            de: 'SEO',
            fr: 'SEO',
          },
          fields: [], // the slug field is autogenerated
        },
      ],
    },
  ],

  admin: {
    group: AdminPanelDashboardGroups.StaticPages,
    description: {
      en: 'Settings for the data privacy statement',
      de: 'Einstellungen für die Datenschutzerklärung',
      fr: 'Paramètres pour la déclaration de confidentialité',
    },
  },
});
