import { GlobalConfig } from 'payload';
import { AdminPanelDashboardGroups } from '@/payload-cms/admin-panel-dashboard-groups';
import { asLocalizedGlobal } from '@/payload-cms/utils/localized-global';
import { localizedDefaultValue } from '@/payload-cms/utils/localized-default-value';

export const SearchGlobal: GlobalConfig = asLocalizedGlobal({
  slug: 'search',
  label: {
    de: 'Suche',
    en: 'Search',
    fr: 'Recherche',
  },
  fields: [
    {
      type: 'tabs',
      tabs: [
        {
          name: 'content',
          label: {
            en: 'Content',
            de: 'Seiteninhalt',
            fr: 'Contenu',
          },
          fields: [
            {
              name: 'pageTitle',
              label: {
                en: 'Page Title',
                de: 'Seitentitel',
                fr: 'Titre de la page',
              },
              type: 'text',
              required: true,
              localized: true,
              defaultValue: localizedDefaultValue({
                de: 'Suche',
                en: 'Search',
                fr: 'Recherche',
              }),
              admin: {
                readOnly: true,
                description: {
                  en: 'This is the title that will be displayed on the page.',
                  de: 'Dies ist der Titel, der auf der Seite angezeigt wird.',
                  fr: "C'est le titre qui sera affiché sur la page.",
                },
              },
            },
          ],
        },
        {
          name: 'seo',
          label: {
            en: 'SEO',
            de: 'SEO',
            fr: 'SEO',
          },
          fields: [], // the slug field is autogenerated
        },
      ],
    },
  ],
  admin: {
    group: AdminPanelDashboardGroups.StaticPages,
    description: {
      en: 'Settings for the search page',
      de: 'Einstellungen für die Suche',
      fr: 'Paramètres pour la page recherche',
    },
  },
});
