name: Bug Report
description: File a bug report.
title: '[Bug]: '
labels: ['bug']
body:
  - type: text
    id: bug-platform
    attributes:
      label: Where did the bug occur? (Web, iOS, Android)
      placeholder:
      value:
    validation:
      required: true
  - type: textarea
    id: bug-report
    attributes:
      label: What is the bug?
      description: What should happen?
      placeholder:
      value:
    validations:
      required: true
