/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This field indicates whether the document is published in the corresponding locale
 */
export type IsPublishedInCorrespondingLocale = boolean;
/**
 * The ID of the group as used in the CeviDB.
 */
export type TheIDOfTheGroup = number;
/**
 * The name of the group as used in the CeviDB.
 */
export type TheNameOfTheGroup = string;
/**
 * The name of the role the user has in the group.
 */
export type TheNameOfTheRole = string;
/**
 * The class of the role the user has in the group.
 */
export type TheClassOfTheRole = string;
/**
 * The groups the user is in as extracted from the CeviDB profile.
 */
export type GroupsOfTheUser = {
  id: TheIDOfTheGroup;
  name: TheNameOfTheGroup;
  role_name: TheNameOfTheRole;
  role_class: TheClassOfTheRole;
  [k: string]: unknown;
}[];
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones = 'Europe/Zurich';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    blog: Blog;
    'generic-page': GenericPage;
    timeline: Timeline;
    'camp-map-annotations': CampMapAnnotation;
    'camp-schedule-entry': CampScheduleEntry;
    images: Image;
    userSubmittedImages: UserSubmittedImage;
    documents: Document;
    users: User;
    permissions: Permission;
    'push-notification-subscriptions': PushNotificationSubscription;
    timelineCategory: TimelineCategory;
    forms: Form;
    'form-submissions': FormSubmission;
    'search-collection': SearchCollection;
    go: Go;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    timelineCategory: {
      relatedTimelineEntries: 'timeline';
    };
    forms: {
      submissions: 'form-submissions';
    };
  };
  collectionsSelect: {
    blog: BlogSelect<false> | BlogSelect<true>;
    'generic-page': GenericPageSelect<false> | GenericPageSelect<true>;
    timeline: TimelineSelect<false> | TimelineSelect<true>;
    'camp-map-annotations': CampMapAnnotationsSelect<false> | CampMapAnnotationsSelect<true>;
    'camp-schedule-entry': CampScheduleEntrySelect<false> | CampScheduleEntrySelect<true>;
    images: ImagesSelect<false> | ImagesSelect<true>;
    userSubmittedImages: UserSubmittedImagesSelect<false> | UserSubmittedImagesSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    permissions: PermissionsSelect<false> | PermissionsSelect<true>;
    'push-notification-subscriptions': PushNotificationSubscriptionsSelect<false> | PushNotificationSubscriptionsSelect<true>;
    timelineCategory: TimelineCategorySelect<false> | TimelineCategorySelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'search-collection': SearchCollectionSelect<false> | SearchCollectionSelect<true>;
    go: GoSelect<false> | GoSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'de' | 'fr') | ('en' | 'de' | 'fr')[];
  globals: {
    header: Header;
    footer: Footer;
    SEO: SEO;
    PWA: PWA;
    alert_settings: AlertSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    SEO: SEOSelect<false> | SEOSelect<true>;
    PWA: PWASelect<false> | PWASelect<true>;
    alert_settings: AlertSettingsSelect<false> | AlertSettingsSelect<true>;
  };
  locale: 'en' | 'de' | 'fr';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Represents a block article that can be published on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: string;
  publishingStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  _localized_status: LocalizedPublishingStatus;
  _disable_unpublishing?: boolean | null;
  _locale: string;
  /**
   * Name of the page for internal purposes.
   */
  internalPageName: string;
  /**
   * Authors of the Page (internal use only)
   */
  authors?: (string | User)[] | null;
  /**
   * Status of the page (internal use)
   */
  internalStatus: 'draft' | 'translation' | 'review' | 'approved' | 'archived';
  content: {
    /**
     * This is the title that will be displayed on the page.
     */
    blogH1: string;
    bannerImage: string | Image;
    releaseDate: string;
    permissions?: (string | null) | Permission;
    /**
     * This is the text that will be displayed as a teaser on the blog overview page.
     */
    blogShortTitle: string;
    /**
     * The main content of the page
     */
    mainContent: (
      | {
          richTextSection: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          id?: string | null;
          blockName?: string | null;
          blockType: 'richTextSection';
        }
      | {
          id?: string | null;
          blockName?: string | null;
          blockType: 'blogPostsOverview';
        }
      | FormBlock
      | {
          images: (string | Image)[];
          id?: string | null;
          blockName?: string | null;
          blockType: 'photoCarousel';
        }
      | {
          image: string | Image;
          id?: string | null;
          blockName?: string | null;
          blockType: 'singlePicture';
        }
      | YoutubeEmbedding
      | InstagramEmbedding
      | SwisstopoMapEmbedding
      | {
          file: string | Document;
          openInNewTab?: boolean | null;
          id?: string | null;
          blockName?: string | null;
          blockType: 'fileDownload';
        }
      | DetailsTable
      | AccordionBlocks
      | SummaryBox
      | TimelineEntries
      | Countdown
      | {
          id?: string | null;
          blockName?: string | null;
          blockType: 'whiteSpace';
        }
      | {
          /**
           * Label for the button
           */
          label?: string | null;
          linkField?: {
            type?: ('reference' | 'custom') | null;
            reference?:
              | ({
                  relationTo: 'blog';
                  value: string | Blog;
                } | null)
              | ({
                  relationTo: 'generic-page';
                  value: string | GenericPage;
                } | null)
              | ({
                  relationTo: 'images';
                  value: string | Image;
                } | null)
              | ({
                  relationTo: 'documents';
                  value: string | Document;
                } | null)
              | ({
                  relationTo: 'camp-map-annotations';
                  value: string | CampMapAnnotation;
                } | null)
              | ({
                  relationTo: 'camp-schedule-entry';
                  value: string | CampScheduleEntry;
                } | null);
            url?: string | null;
            openInNewTab?: boolean | null;
          };
          /**
           * Show inverted colors
           */
          inverted?: boolean | null;
          id?: string | null;
          blockName?: string | null;
          blockType: 'callToAction';
        }
      | {
          linkField?: {
            type?: ('reference' | 'custom') | null;
            reference?:
              | ({
                  relationTo: 'blog';
                  value: string | Blog;
                } | null)
              | ({
                  relationTo: 'generic-page';
                  value: string | GenericPage;
                } | null)
              | ({
                  relationTo: 'images';
                  value: string | Image;
                } | null)
              | ({
                  relationTo: 'documents';
                  value: string | Document;
                } | null)
              | ({
                  relationTo: 'camp-map-annotations';
                  value: string | CampMapAnnotation;
                } | null)
              | ({
                  relationTo: 'camp-schedule-entry';
                  value: string | CampScheduleEntry;
                } | null);
            url?: string | null;
            openInNewTab?: boolean | null;
          };
          headline: string;
          date: string;
          image?: (string | null) | Image;
          paragraph?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          id?: string | null;
          blockName?: string | null;
          blockType: 'newsCard';
        }
      | {
          date: string;
          location?: (string | null) | CampMapAnnotation;
          id?: string | null;
          blockName?: string | null;
          blockType: 'campScheduleEntryBlock';
        }
    )[];
  };
  seo: {
    urlSlug: string;
    /**
     * This is the title that will be displayed in the browser tab.
     */
    metaTitle?: string | null;
    /**
     * This is the description that will be displayed in search engine results.
     */
    metaDescription?: string | null;
    /**
     * These are the keywords that will be used to improve the visibility of the page in search engines.
     */
    keywords?: string | null;
  };
  lastEditedByUser?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Holds the publishing status of the document in each locale
 */
export interface LocalizedPublishingStatus {
  published: IsPublishedInCorrespondingLocale;
  [k: string]: unknown;
}
/**
 * Represents a Hitobito user. These information get automatically synced whenever the user logs in.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * The ID of the user in the CeviDB.
   */
  cevi_db_uuid: number;
  /**
   * Whether the user has access to the admin panel. This is set automatically based on the user groups.
   */
  adminPanelAccess?: boolean | null;
  email: string;
  /**
   * The full name of the user, as it will be displayed publicly.
   */
  fullName: string;
  /**
   * The Ceviname of the user.
   */
  nickname?: string | null;
  groups: GroupsOfTheUser;
  /**
   * The Hof of the user.
   */
  hof?: number | null;
  /**
   * The Quartier of the user.
   */
  quartier?: number | null;
  lastEditedByUser?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images".
 */
export interface Image {
  id: string;
  /**
   * Describe the image for screen readers. (de)
   */
  alt_de: string;
  /**
   * Describe the image for screen readers. (en)
   */
  alt_en: string;
  /**
   * Describe the image for screen readers. (fr)
   */
  alt_fr: string;
  /**
   * Optional text to display below the image (e.g. image source, copyright information, explanatory text) (de)
   */
  imageCaption_de?: string | null;
  /**
   * Optional text to display below the image (e.g. image source, copyright information, explanatory text) (en)
   */
  imageCaption_en?: string | null;
  /**
   * Optional text to display below the image (e.g. image source, copyright information, explanatory text) (fr)
   */
  imageCaption_fr?: string | null;
  lastEditedByUser?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    tiny?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions".
 */
export interface Permission {
  id: string;
  /**
   * The name of the permission.
   */
  permissionName: string;
  /**
   * List of Groups in the CeviDB for this permission. Disables the special permissions section.
   */
  permissions?:
    | {
        group_id: number;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * These permissions are special and disable group checking for CeviDB groups.
   */
  special_permissions?: {
    public?: boolean | null;
    logged_in?: boolean | null;
  };
  lastEditedByUser?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  autocomplete?: boolean | null;
  sections: {
    formSection: {
      sectionTitle: string;
      fields?:
        | (
            | {
                name: string;
                label: {
                  root: {
                    type: string;
                    children: {
                      type: any;
                      version: number;
                      [k: string]: unknown;
                    }[];
                    direction: ('ltr' | 'rtl') | null;
                    format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                    indent: number;
                    version: number;
                  };
                  [k: string]: unknown;
                };
                required?: boolean | null;
                defaultValue?: boolean | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'checkbox';
              }
            | {
                name: string;
                label: string;
                required?: boolean | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'country';
              }
            | {
                name: string;
                label: string;
                placeholder?: string | null;
                required?: boolean | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'email';
              }
            | {
                message?: {
                  root: {
                    type: string;
                    children: {
                      type: any;
                      version: number;
                      [k: string]: unknown;
                    }[];
                    direction: ('ltr' | 'rtl') | null;
                    format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                    indent: number;
                    version: number;
                  };
                  [k: string]: unknown;
                } | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'message';
              }
            | {
                name: string;
                label: string;
                defaultValue?: number | null;
                placeholder?: string | null;
                required?: boolean | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'number';
              }
            | {
                name: string;
                label: string;
                defaultValue?: string | null;
                placeholder?: string | null;
                allowMultiple?: boolean | null;
                /**
                 * Choose whether the options should be displayed as a dropdown, cards boxes, or radio buttons.
                 */
                optionType?: ('dropdown' | 'cards' | 'radio') | null;
                options?:
                  | {
                      value: string;
                      label: string;
                      id?: string | null;
                    }[]
                  | null;
                required?: boolean | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'select';
              }
            | {
                name: string;
                label: string;
                placeholder?: string | null;
                defaultValue?: string | null;
                /**
                 * Required field
                 */
                required?: boolean | null;
                /**
                 * Use a regular expression to validate the input. For example, "^[a-zA-Z0-9]+$" will only allow alphanumeric characters.
                 */
                inputValidation?: string | null;
                /**
                 * Custom error message to display when the input does not match the validation regex.
                 */
                inputValidationErrorMessage?: string | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'text';
              }
            | {
                name: string;
                label: string;
                placeholder?: string | null;
                defaultValue?: string | null;
                required?: boolean | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'textarea';
              }
            | {
                name: string;
                label: string;
                defaultValue?: string | null;
                required?: boolean | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'date';
              }
            | {
                displayCondition?: {
                  field?: string | null;
                  value?: string | null;
                };
                fields?:
                  | (
                      | {
                          name: string;
                          label: {
                            root: {
                              type: string;
                              children: {
                                type: any;
                                version: number;
                                [k: string]: unknown;
                              }[];
                              direction: ('ltr' | 'rtl') | null;
                              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                              indent: number;
                              version: number;
                            };
                            [k: string]: unknown;
                          };
                          required?: boolean | null;
                          defaultValue?: boolean | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'checkbox';
                        }
                      | {
                          name: string;
                          label: string;
                          required?: boolean | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'country';
                        }
                      | {
                          name: string;
                          label: string;
                          placeholder?: string | null;
                          required?: boolean | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'email';
                        }
                      | {
                          message?: {
                            root: {
                              type: string;
                              children: {
                                type: any;
                                version: number;
                                [k: string]: unknown;
                              }[];
                              direction: ('ltr' | 'rtl') | null;
                              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                              indent: number;
                              version: number;
                            };
                            [k: string]: unknown;
                          } | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'message';
                        }
                      | {
                          name: string;
                          label: string;
                          defaultValue?: number | null;
                          placeholder?: string | null;
                          required?: boolean | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'number';
                        }
                      | {
                          name: string;
                          label: string;
                          defaultValue?: string | null;
                          placeholder?: string | null;
                          allowMultiple?: boolean | null;
                          /**
                           * Choose whether the options should be displayed as a dropdown, cards boxes, or radio buttons.
                           */
                          optionType?: ('dropdown' | 'cards' | 'radio') | null;
                          options?:
                            | {
                                value: string;
                                label: string;
                                id?: string | null;
                              }[]
                            | null;
                          required?: boolean | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'select';
                        }
                      | {
                          name: string;
                          label: string;
                          placeholder?: string | null;
                          defaultValue?: string | null;
                          /**
                           * Required field
                           */
                          required?: boolean | null;
                          /**
                           * Use a regular expression to validate the input. For example, "^[a-zA-Z0-9]+$" will only allow alphanumeric characters.
                           */
                          inputValidation?: string | null;
                          /**
                           * Custom error message to display when the input does not match the validation regex.
                           */
                          inputValidationErrorMessage?: string | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'text';
                        }
                      | {
                          name: string;
                          label: string;
                          placeholder?: string | null;
                          defaultValue?: string | null;
                          required?: boolean | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'textarea';
                        }
                      | {
                          name: string;
                          label: string;
                          defaultValue?: string | null;
                          required?: boolean | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'date';
                        }
                    )[]
                  | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'conditionedBlock';
              }
          )[]
        | null;
    };
    id?: string | null;
  }[];
  submitButtonLabel: string;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  submissions?: {
    docs?: (string | FormSubmission)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  publishingStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  _localized_status: LocalizedPublishingStatus;
  _disable_unpublishing?: boolean | null;
  _locale: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "YoutubeEmbedding".
 */
export interface YoutubeEmbedding {
  /**
   * Links to the Youtube videos
   */
  links?:
    | {
        /**
         * Link to the Youtube video
         */
        link: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'youtubeEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InstagramEmbedding".
 */
export interface InstagramEmbedding {
  /**
   * Link to the Instagram post
   */
  link: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'instagramEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SwisstopoMapEmbedding".
 */
export interface SwisstopoMapEmbedding {
  initialMapPose?: {
    zoom?: number | null;
    /**
     * @minItems 2
     * @maxItems 2
     */
    initialMapCenter?: [number, number] | null;
  };
  /**
   * Markers on the map with a small Cevi logo
   */
  ceviLogoMarkers?:
    | {
        title?: string | null;
        /**
         * Coordinates of the annotation on the map.
         */
        geometry?: {
          /**
           * Coordinates of the annotation on the map.
           *
           * @minItems 2
           * @maxItems 2
           */
          coordinates?: [number, number] | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'swisstopoEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: string;
  permissions?: (string | null) | Permission;
  lastEditedByUser?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DetailsTable".
 */
export interface DetailsTable {
  introduction: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  detailsTableBlocks?:
    | {
        label: string;
        value: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'detailsTable';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlocks".
 */
export interface AccordionBlocks {
  introduction?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  accordionBlocks?:
    | {
        /**
         * Choose whether to display the title or a portrait in the miniaturized view.
         */
        titleOrPortrait: 'title' | 'portrait';
        /**
         * This is the title of the accordion block. It will be displayed in the overview, and when clicked, the block will expand.
         */
        title?: string | null;
        teamLeaderGroup?: {
          name: string;
          ceviname?: string | null;
          portrait?: (string | null) | Image;
        };
        /**
         * This is the content of the accordion block. It will be displayed when the block is expanded.
         */
        valueBlocks: (PlainTextBlock | TeamMembersBlock | FormBlock)[];
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PlainTextBlock".
 */
export interface PlainTextBlock {
  value: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordionPlainTextBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamMembersBlock".
 */
export interface TeamMembersBlock {
  linkField?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'blog';
          value: string | Blog;
        } | null)
      | ({
          relationTo: 'generic-page';
          value: string | GenericPage;
        } | null)
      | ({
          relationTo: 'images';
          value: string | Image;
        } | null)
      | ({
          relationTo: 'documents';
          value: string | Document;
        } | null)
      | ({
          relationTo: 'camp-map-annotations';
          value: string | CampMapAnnotation;
        } | null)
      | ({
          relationTo: 'camp-schedule-entry';
          value: string | CampScheduleEntry;
        } | null);
    url?: string | null;
    openInNewTab?: boolean | null;
  };
  teamLeaderGroup: {
    name: string;
    ceviname?: string | null;
    portrait?: (string | null) | Image;
  };
  teamMembers?:
    | {
        name: string;
        ceviname?: string | null;
        function: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordionTeamMembersBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generic-page".
 */
export interface GenericPage {
  id: string;
  publishingStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  _localized_status: LocalizedPublishingStatus;
  _disable_unpublishing?: boolean | null;
  _locale: string;
  /**
   * Name of the page for internal purposes.
   */
  internalPageName: string;
  /**
   * Authors of the Page (internal use only)
   */
  authors?: (string | User)[] | null;
  /**
   * Status of the page (internal use)
   */
  internalStatus: 'draft' | 'translation' | 'review' | 'approved' | 'archived';
  content: {
    /**
     * This is the title that will be displayed on the page.
     */
    pageTitle: string;
    permissions?: (string | null) | Permission;
    releaseDate: string;
    /**
     * The main content of the page
     */
    mainContent: (
      | {
          richTextSection: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          id?: string | null;
          blockName?: string | null;
          blockType: 'richTextSection';
        }
      | {
          id?: string | null;
          blockName?: string | null;
          blockType: 'blogPostsOverview';
        }
      | FormBlock
      | {
          images: (string | Image)[];
          id?: string | null;
          blockName?: string | null;
          blockType: 'photoCarousel';
        }
      | {
          image: string | Image;
          id?: string | null;
          blockName?: string | null;
          blockType: 'singlePicture';
        }
      | YoutubeEmbedding
      | InstagramEmbedding
      | SwisstopoMapEmbedding
      | {
          file: string | Document;
          openInNewTab?: boolean | null;
          id?: string | null;
          blockName?: string | null;
          blockType: 'fileDownload';
        }
      | DetailsTable
      | AccordionBlocks
      | SummaryBox
      | TimelineEntries
      | Countdown
      | {
          id?: string | null;
          blockName?: string | null;
          blockType: 'whiteSpace';
        }
      | {
          /**
           * Label for the button
           */
          label?: string | null;
          linkField?: {
            type?: ('reference' | 'custom') | null;
            reference?:
              | ({
                  relationTo: 'blog';
                  value: string | Blog;
                } | null)
              | ({
                  relationTo: 'generic-page';
                  value: string | GenericPage;
                } | null)
              | ({
                  relationTo: 'images';
                  value: string | Image;
                } | null)
              | ({
                  relationTo: 'documents';
                  value: string | Document;
                } | null)
              | ({
                  relationTo: 'camp-map-annotations';
                  value: string | CampMapAnnotation;
                } | null)
              | ({
                  relationTo: 'camp-schedule-entry';
                  value: string | CampScheduleEntry;
                } | null);
            url?: string | null;
            openInNewTab?: boolean | null;
          };
          /**
           * Show inverted colors
           */
          inverted?: boolean | null;
          id?: string | null;
          blockName?: string | null;
          blockType: 'callToAction';
        }
      | {
          linkField?: {
            type?: ('reference' | 'custom') | null;
            reference?:
              | ({
                  relationTo: 'blog';
                  value: string | Blog;
                } | null)
              | ({
                  relationTo: 'generic-page';
                  value: string | GenericPage;
                } | null)
              | ({
                  relationTo: 'images';
                  value: string | Image;
                } | null)
              | ({
                  relationTo: 'documents';
                  value: string | Document;
                } | null)
              | ({
                  relationTo: 'camp-map-annotations';
                  value: string | CampMapAnnotation;
                } | null)
              | ({
                  relationTo: 'camp-schedule-entry';
                  value: string | CampScheduleEntry;
                } | null);
            url?: string | null;
            openInNewTab?: boolean | null;
          };
          headline: string;
          date: string;
          image?: (string | null) | Image;
          paragraph?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          id?: string | null;
          blockName?: string | null;
          blockType: 'newsCard';
        }
      | {
          date: string;
          location?: (string | null) | CampMapAnnotation;
          id?: string | null;
          blockName?: string | null;
          blockType: 'campScheduleEntryBlock';
        }
    )[];
  };
  seo: {
    urlSlug: string;
    /**
     * This is the title that will be displayed in the browser tab.
     */
    metaTitle?: string | null;
    /**
     * This is the description that will be displayed in search engine results.
     */
    metaDescription?: string | null;
    /**
     * These are the keywords that will be used to improve the visibility of the page in search engines.
     */
    keywords?: string | null;
  };
  lastEditedByUser?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "summaryBox".
 */
export interface SummaryBox {
  richTextSection: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'summaryBox';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timelineEntries".
 */
export interface TimelineEntries {
  timelineEntryCategories?: (string | TimelineCategory)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'timelineEntries';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timelineCategory".
 */
export interface TimelineCategory {
  id: string;
  name: string;
  description?: string | null;
  relatedTimelineEntries?: {
    docs?: (string | Timeline)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Represents a timeline that can be published on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline".
 */
export interface Timeline {
  id: string;
  publishingStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  _localized_status: LocalizedPublishingStatus;
  _disable_unpublishing?: boolean | null;
  _locale: string;
  /**
   * Name of the page for internal purposes.
   */
  internalPageName: string;
  /**
   * Authors of the Page (internal use only)
   */
  authors?: (string | User)[] | null;
  /**
   * Status of the page (internal use)
   */
  internalStatus: 'draft' | 'translation' | 'review' | 'approved' | 'archived';
  date: string;
  dateFormat?: ('fullDateAndTime' | 'fullDate' | 'yearAndMonth') | null;
  /**
   * This is the title that will be displayed on the page.
   */
  title: string;
  /**
   * The main content of the page
   */
  mainContent?:
    | (
        | {
            richTextSection: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richTextSection';
          }
        | {
            image: string | Image;
            id?: string | null;
            blockName?: string | null;
            blockType: 'singlePicture';
          }
        | InstagramEmbedding
      )[]
    | null;
  categories?: (string | TimelineCategory)[] | null;
  lastEditedByUser?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countdown".
 */
export interface Countdown {
  endDate: string;
  /**
   * Optional title for the countdown block.
   */
  title?: string | null;
  /**
   * Optional description for the countdown block.
   */
  descriptionAbove?: string | null;
  /**
   * Optional description for the countdown block.
   */
  descriptionBelow?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'countdown';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "camp-map-annotations".
 */
export interface CampMapAnnotation {
  id: string;
  /**
   * The title of the annotation.
   */
  title: string;
  icon?:
    | (
        | 'MapPin'
        | 'Tent'
        | 'Utensils'
        | 'Flag'
        | 'HelpCircle'
        | 'Recycle'
        | 'GlassWater'
        | 'Stage'
        | 'Toilet'
        | 'BriefcaseMedical'
      )
    | null;
  color?: ('#78909c' | '#fbc02d' | '#ff8126' | '#b56aff' | '#f848c7' | '#16a672' | '#f64955') | null;
  /**
   * A detailed description of the annotation.
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  openingHours?:
    | {
        day?: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday') | null;
        /**
         * Opening hours in HH:mm format (e.g., 08:00 - 18:00)
         */
        time: string;
        id?: string | null;
      }[]
    | null;
  images?: (string | Image)[] | null;
  annotationType: 'marker' | 'polygon';
  /**
   * Coordinates of the annotation on the map.
   */
  geometry?: {
    /**
     * Coordinates of the annotation on the map.
     *
     * @minItems 2
     * @maxItems 2
     */
    coordinates?: [number, number] | null;
  };
  /**
   * Enter the coordinates for the polygon. A closed polygon requires at least 3 points.
   */
  polygonCoordinates?:
    | {
        latitude: number;
        longitude: number;
        id?: string | null;
      }[]
    | null;
  lastEditedByUser?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "camp-schedule-entry".
 */
export interface CampScheduleEntry {
  id: string;
  /**
   * The title of the entry.
   */
  title: string;
  /**
   * The description of the entry
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Time slots for the schedule entry
   */
  timeslot: {
    date: string;
    /**
     * Time slots in HH:mm format (e.g., 08:00 - 18:00)
     */
    time: string;
  };
  /**
   * Location of the Schedule Entry
   */
  location: string | CampMapAnnotation;
  /**
   * Organiser
   */
  organiser?: (string | null) | User;
  participants_min?: number | null;
  participants_max?: number | null;
  lastEditedByUser?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "userSubmittedImages".
 */
export interface UserSubmittedImage {
  id: string;
  uploaded_by: string | User;
  original_filename?: string | null;
  user_description: string;
  lastEditedByUser?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    tiny?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-notification-subscriptions".
 */
export interface PushNotificationSubscription {
  id: string;
  user?: (string | null) | User;
  endpoint: string;
  expirationTime?: number | null;
  keys: {
    p256dh: string;
    auth: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search-collection".
 */
export interface SearchCollection {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'blog';
        value: string | Blog;
      }
    | {
        relationTo: 'generic-page';
        value: string | GenericPage;
      };
  /**
   * This field is used for search indexing. It is automatically filled and not editable.
   */
  search_content?: string | null;
  search_title?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "go".
 */
export interface Go {
  id: string;
  urlSlug: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'blog';
          value: string | Blog;
        } | null)
      | ({
          relationTo: 'generic-page';
          value: string | GenericPage;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'blog';
        value: string | Blog;
      } | null)
    | ({
        relationTo: 'generic-page';
        value: string | GenericPage;
      } | null)
    | ({
        relationTo: 'timeline';
        value: string | Timeline;
      } | null)
    | ({
        relationTo: 'camp-map-annotations';
        value: string | CampMapAnnotation;
      } | null)
    | ({
        relationTo: 'camp-schedule-entry';
        value: string | CampScheduleEntry;
      } | null)
    | ({
        relationTo: 'images';
        value: string | Image;
      } | null)
    | ({
        relationTo: 'userSubmittedImages';
        value: string | UserSubmittedImage;
      } | null)
    | ({
        relationTo: 'documents';
        value: string | Document;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'permissions';
        value: string | Permission;
      } | null)
    | ({
        relationTo: 'push-notification-subscriptions';
        value: string | PushNotificationSubscription;
      } | null)
    | ({
        relationTo: 'timelineCategory';
        value: string | TimelineCategory;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search-collection';
        value: string | SearchCollection;
      } | null)
    | ({
        relationTo: 'go';
        value: string | Go;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  publishingStatus?: T;
  _localized_status?: T;
  _disable_unpublishing?: T;
  _locale?: T;
  internalPageName?: T;
  authors?: T;
  internalStatus?: T;
  content?:
    | T
    | {
        blogH1?: T;
        bannerImage?: T;
        releaseDate?: T;
        permissions?: T;
        blogShortTitle?: T;
        mainContent?:
          | T
          | {
              richTextSection?:
                | T
                | {
                    richTextSection?: T;
                    id?: T;
                    blockName?: T;
                  };
              blogPostsOverview?:
                | T
                | {
                    id?: T;
                    blockName?: T;
                  };
              formBlock?: T | FormBlockSelect<T>;
              photoCarousel?:
                | T
                | {
                    images?: T;
                    id?: T;
                    blockName?: T;
                  };
              singlePicture?:
                | T
                | {
                    image?: T;
                    id?: T;
                    blockName?: T;
                  };
              youtubeEmbed?: T | YoutubeEmbeddingSelect<T>;
              instagramEmbed?: T | InstagramEmbeddingSelect<T>;
              swisstopoEmbed?: T | SwisstopoMapEmbeddingSelect<T>;
              fileDownload?:
                | T
                | {
                    file?: T;
                    openInNewTab?: T;
                    id?: T;
                    blockName?: T;
                  };
              detailsTable?: T | DetailsTableSelect<T>;
              accordion?: T | AccordionBlocksSelect<T>;
              summaryBox?: T | SummaryBoxSelect<T>;
              timelineEntries?: T | TimelineEntriesSelect<T>;
              countdown?: T | CountdownSelect<T>;
              whiteSpace?:
                | T
                | {
                    id?: T;
                    blockName?: T;
                  };
              callToAction?:
                | T
                | {
                    label?: T;
                    linkField?:
                      | T
                      | {
                          type?: T;
                          reference?: T;
                          url?: T;
                          openInNewTab?: T;
                        };
                    inverted?: T;
                    id?: T;
                    blockName?: T;
                  };
              newsCard?:
                | T
                | {
                    linkField?:
                      | T
                      | {
                          type?: T;
                          reference?: T;
                          url?: T;
                          openInNewTab?: T;
                        };
                    headline?: T;
                    date?: T;
                    image?: T;
                    paragraph?: T;
                    id?: T;
                    blockName?: T;
                  };
              campScheduleEntryBlock?:
                | T
                | {
                    date?: T;
                    location?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  seo?:
    | T
    | {
        urlSlug?: T;
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
      };
  lastEditedByUser?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "YoutubeEmbedding_select".
 */
export interface YoutubeEmbeddingSelect<T extends boolean = true> {
  links?:
    | T
    | {
        link?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InstagramEmbedding_select".
 */
export interface InstagramEmbeddingSelect<T extends boolean = true> {
  link?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SwisstopoMapEmbedding_select".
 */
export interface SwisstopoMapEmbeddingSelect<T extends boolean = true> {
  initialMapPose?:
    | T
    | {
        zoom?: T;
        initialMapCenter?: T;
      };
  ceviLogoMarkers?:
    | T
    | {
        title?: T;
        geometry?:
          | T
          | {
              coordinates?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DetailsTable_select".
 */
export interface DetailsTableSelect<T extends boolean = true> {
  introduction?: T;
  detailsTableBlocks?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlocks_select".
 */
export interface AccordionBlocksSelect<T extends boolean = true> {
  introduction?: T;
  accordionBlocks?:
    | T
    | {
        titleOrPortrait?: T;
        title?: T;
        teamLeaderGroup?:
          | T
          | {
              name?: T;
              ceviname?: T;
              portrait?: T;
            };
        valueBlocks?:
          | T
          | {
              accordionPlainTextBlock?: T | PlainTextBlockSelect<T>;
              accordionTeamMembersBlock?: T | TeamMembersBlockSelect<T>;
              formBlock?: T | FormBlockSelect<T>;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PlainTextBlock_select".
 */
export interface PlainTextBlockSelect<T extends boolean = true> {
  value?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamMembersBlock_select".
 */
export interface TeamMembersBlockSelect<T extends boolean = true> {
  linkField?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
        openInNewTab?: T;
      };
  teamLeaderGroup?:
    | T
    | {
        name?: T;
        ceviname?: T;
        portrait?: T;
      };
  teamMembers?:
    | T
    | {
        name?: T;
        ceviname?: T;
        function?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "summaryBox_select".
 */
export interface SummaryBoxSelect<T extends boolean = true> {
  richTextSection?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timelineEntries_select".
 */
export interface TimelineEntriesSelect<T extends boolean = true> {
  timelineEntryCategories?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countdown_select".
 */
export interface CountdownSelect<T extends boolean = true> {
  endDate?: T;
  title?: T;
  descriptionAbove?: T;
  descriptionBelow?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generic-page_select".
 */
export interface GenericPageSelect<T extends boolean = true> {
  publishingStatus?: T;
  _localized_status?: T;
  _disable_unpublishing?: T;
  _locale?: T;
  internalPageName?: T;
  authors?: T;
  internalStatus?: T;
  content?:
    | T
    | {
        pageTitle?: T;
        permissions?: T;
        releaseDate?: T;
        mainContent?:
          | T
          | {
              richTextSection?:
                | T
                | {
                    richTextSection?: T;
                    id?: T;
                    blockName?: T;
                  };
              blogPostsOverview?:
                | T
                | {
                    id?: T;
                    blockName?: T;
                  };
              formBlock?: T | FormBlockSelect<T>;
              photoCarousel?:
                | T
                | {
                    images?: T;
                    id?: T;
                    blockName?: T;
                  };
              singlePicture?:
                | T
                | {
                    image?: T;
                    id?: T;
                    blockName?: T;
                  };
              youtubeEmbed?: T | YoutubeEmbeddingSelect<T>;
              instagramEmbed?: T | InstagramEmbeddingSelect<T>;
              swisstopoEmbed?: T | SwisstopoMapEmbeddingSelect<T>;
              fileDownload?:
                | T
                | {
                    file?: T;
                    openInNewTab?: T;
                    id?: T;
                    blockName?: T;
                  };
              detailsTable?: T | DetailsTableSelect<T>;
              accordion?: T | AccordionBlocksSelect<T>;
              summaryBox?: T | SummaryBoxSelect<T>;
              timelineEntries?: T | TimelineEntriesSelect<T>;
              countdown?: T | CountdownSelect<T>;
              whiteSpace?:
                | T
                | {
                    id?: T;
                    blockName?: T;
                  };
              callToAction?:
                | T
                | {
                    label?: T;
                    linkField?:
                      | T
                      | {
                          type?: T;
                          reference?: T;
                          url?: T;
                          openInNewTab?: T;
                        };
                    inverted?: T;
                    id?: T;
                    blockName?: T;
                  };
              newsCard?:
                | T
                | {
                    linkField?:
                      | T
                      | {
                          type?: T;
                          reference?: T;
                          url?: T;
                          openInNewTab?: T;
                        };
                    headline?: T;
                    date?: T;
                    image?: T;
                    paragraph?: T;
                    id?: T;
                    blockName?: T;
                  };
              campScheduleEntryBlock?:
                | T
                | {
                    date?: T;
                    location?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  seo?:
    | T
    | {
        urlSlug?: T;
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
      };
  lastEditedByUser?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline_select".
 */
export interface TimelineSelect<T extends boolean = true> {
  publishingStatus?: T;
  _localized_status?: T;
  _disable_unpublishing?: T;
  _locale?: T;
  internalPageName?: T;
  authors?: T;
  internalStatus?: T;
  date?: T;
  dateFormat?: T;
  title?: T;
  mainContent?:
    | T
    | {
        richTextSection?:
          | T
          | {
              richTextSection?: T;
              id?: T;
              blockName?: T;
            };
        singlePicture?:
          | T
          | {
              image?: T;
              id?: T;
              blockName?: T;
            };
        instagramEmbed?: T | InstagramEmbeddingSelect<T>;
      };
  categories?: T;
  lastEditedByUser?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "camp-map-annotations_select".
 */
export interface CampMapAnnotationsSelect<T extends boolean = true> {
  title?: T;
  icon?: T;
  color?: T;
  description?: T;
  openingHours?:
    | T
    | {
        day?: T;
        time?: T;
        id?: T;
      };
  images?: T;
  annotationType?: T;
  geometry?:
    | T
    | {
        coordinates?: T;
      };
  polygonCoordinates?:
    | T
    | {
        latitude?: T;
        longitude?: T;
        id?: T;
      };
  lastEditedByUser?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "camp-schedule-entry_select".
 */
export interface CampScheduleEntrySelect<T extends boolean = true> {
  title?: T;
  description?: T;
  timeslot?:
    | T
    | {
        date?: T;
        time?: T;
      };
  location?: T;
  organiser?: T;
  participants_min?: T;
  participants_max?: T;
  lastEditedByUser?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images_select".
 */
export interface ImagesSelect<T extends boolean = true> {
  alt_de?: T;
  alt_en?: T;
  alt_fr?: T;
  imageCaption_de?: T;
  imageCaption_en?: T;
  imageCaption_fr?: T;
  lastEditedByUser?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        tiny?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "userSubmittedImages_select".
 */
export interface UserSubmittedImagesSelect<T extends boolean = true> {
  uploaded_by?: T;
  original_filename?: T;
  user_description?: T;
  lastEditedByUser?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        tiny?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  permissions?: T;
  lastEditedByUser?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  cevi_db_uuid?: T;
  adminPanelAccess?: T;
  email?: T;
  fullName?: T;
  nickname?: T;
  groups?: T;
  hof?: T;
  quartier?: T;
  lastEditedByUser?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions_select".
 */
export interface PermissionsSelect<T extends boolean = true> {
  permissionName?: T;
  permissions?:
    | T
    | {
        group_id?: T;
        note?: T;
        id?: T;
      };
  special_permissions?:
    | T
    | {
        public?: T;
        logged_in?: T;
      };
  lastEditedByUser?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-notification-subscriptions_select".
 */
export interface PushNotificationSubscriptionsSelect<T extends boolean = true> {
  user?: T;
  endpoint?: T;
  expirationTime?: T;
  keys?:
    | T
    | {
        p256dh?: T;
        auth?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timelineCategory_select".
 */
export interface TimelineCategorySelect<T extends boolean = true> {
  name?: T;
  description?: T;
  relatedTimelineEntries?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  autocomplete?: T;
  sections?:
    | T
    | {
        formSection?:
          | T
          | {
              sectionTitle?: T;
              fields?:
                | T
                | {
                    checkbox?:
                      | T
                      | {
                          name?: T;
                          label?: T;
                          required?: T;
                          defaultValue?: T;
                          id?: T;
                          blockName?: T;
                        };
                    country?:
                      | T
                      | {
                          name?: T;
                          label?: T;
                          required?: T;
                          id?: T;
                          blockName?: T;
                        };
                    email?:
                      | T
                      | {
                          name?: T;
                          label?: T;
                          placeholder?: T;
                          required?: T;
                          id?: T;
                          blockName?: T;
                        };
                    message?:
                      | T
                      | {
                          message?: T;
                          id?: T;
                          blockName?: T;
                        };
                    number?:
                      | T
                      | {
                          name?: T;
                          label?: T;
                          defaultValue?: T;
                          placeholder?: T;
                          required?: T;
                          id?: T;
                          blockName?: T;
                        };
                    select?:
                      | T
                      | {
                          name?: T;
                          label?: T;
                          defaultValue?: T;
                          placeholder?: T;
                          allowMultiple?: T;
                          optionType?: T;
                          options?:
                            | T
                            | {
                                value?: T;
                                label?: T;
                                id?: T;
                              };
                          required?: T;
                          id?: T;
                          blockName?: T;
                        };
                    text?:
                      | T
                      | {
                          name?: T;
                          label?: T;
                          placeholder?: T;
                          defaultValue?: T;
                          required?: T;
                          inputValidation?: T;
                          inputValidationErrorMessage?: T;
                          id?: T;
                          blockName?: T;
                        };
                    textarea?:
                      | T
                      | {
                          name?: T;
                          label?: T;
                          placeholder?: T;
                          defaultValue?: T;
                          required?: T;
                          id?: T;
                          blockName?: T;
                        };
                    date?:
                      | T
                      | {
                          name?: T;
                          label?: T;
                          defaultValue?: T;
                          required?: T;
                          id?: T;
                          blockName?: T;
                        };
                    conditionedBlock?:
                      | T
                      | {
                          displayCondition?:
                            | T
                            | {
                                field?: T;
                                value?: T;
                              };
                          fields?:
                            | T
                            | {
                                checkbox?:
                                  | T
                                  | {
                                      name?: T;
                                      label?: T;
                                      required?: T;
                                      defaultValue?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                country?:
                                  | T
                                  | {
                                      name?: T;
                                      label?: T;
                                      required?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                email?:
                                  | T
                                  | {
                                      name?: T;
                                      label?: T;
                                      placeholder?: T;
                                      required?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                message?:
                                  | T
                                  | {
                                      message?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                number?:
                                  | T
                                  | {
                                      name?: T;
                                      label?: T;
                                      defaultValue?: T;
                                      placeholder?: T;
                                      required?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                select?:
                                  | T
                                  | {
                                      name?: T;
                                      label?: T;
                                      defaultValue?: T;
                                      placeholder?: T;
                                      allowMultiple?: T;
                                      optionType?: T;
                                      options?:
                                        | T
                                        | {
                                            value?: T;
                                            label?: T;
                                            id?: T;
                                          };
                                      required?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                text?:
                                  | T
                                  | {
                                      name?: T;
                                      label?: T;
                                      placeholder?: T;
                                      defaultValue?: T;
                                      required?: T;
                                      inputValidation?: T;
                                      inputValidationErrorMessage?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                textarea?:
                                  | T
                                  | {
                                      name?: T;
                                      label?: T;
                                      placeholder?: T;
                                      defaultValue?: T;
                                      required?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                date?:
                                  | T
                                  | {
                                      name?: T;
                                      label?: T;
                                      defaultValue?: T;
                                      required?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                              };
                          id?: T;
                          blockName?: T;
                        };
                  };
            };
        id?: T;
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  submissions?: T;
  publishingStatus?: T;
  _localized_status?: T;
  _disable_unpublishing?: T;
  _locale?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search-collection_select".
 */
export interface SearchCollectionSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  search_content?: T;
  search_title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "go_select".
 */
export interface GoSelect<T extends boolean = true> {
  urlSlug?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  publishingStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  _localized_status: LocalizedPublishingStatus;
  _locale: string;
  _disable_unpublishing?: boolean | null;
  mainMenu?:
    | {
        label: string;
        linkField?: {
          type?: ('reference' | 'custom') | null;
          reference?:
            | ({
                relationTo: 'blog';
                value: string | Blog;
              } | null)
            | ({
                relationTo: 'generic-page';
                value: string | GenericPage;
              } | null)
            | ({
                relationTo: 'images';
                value: string | Image;
              } | null)
            | ({
                relationTo: 'documents';
                value: string | Document;
              } | null)
            | ({
                relationTo: 'camp-map-annotations';
                value: string | CampMapAnnotation;
              } | null)
            | ({
                relationTo: 'camp-schedule-entry';
                value: string | CampScheduleEntry;
              } | null);
          url?: string | null;
          openInNewTab?: boolean | null;
        };
        subMenu?:
          | {
              label: string;
              linkField?: {
                type?: ('reference' | 'custom') | null;
                reference?:
                  | ({
                      relationTo: 'blog';
                      value: string | Blog;
                    } | null)
                  | ({
                      relationTo: 'generic-page';
                      value: string | GenericPage;
                    } | null)
                  | ({
                      relationTo: 'images';
                      value: string | Image;
                    } | null)
                  | ({
                      relationTo: 'documents';
                      value: string | Document;
                    } | null)
                  | ({
                      relationTo: 'camp-map-annotations';
                      value: string | CampMapAnnotation;
                    } | null)
                  | ({
                      relationTo: 'camp-schedule-entry';
                      value: string | CampScheduleEntry;
                    } | null);
                url?: string | null;
                openInNewTab?: boolean | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Settings for the footer
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  publishingStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  _localized_status: LocalizedPublishingStatus;
  _locale: string;
  _disable_unpublishing?: boolean | null;
  /**
   * Menu item in the dark area of the footer
   */
  minimalFooterMenu?:
    | {
        label: string;
        linkField?: {
          type?: ('reference' | 'custom') | null;
          reference?:
            | ({
                relationTo: 'blog';
                value: string | Blog;
              } | null)
            | ({
                relationTo: 'generic-page';
                value: string | GenericPage;
              } | null)
            | ({
                relationTo: 'images';
                value: string | Image;
              } | null)
            | ({
                relationTo: 'documents';
                value: string | Document;
              } | null)
            | ({
                relationTo: 'camp-map-annotations';
                value: string | CampMapAnnotation;
              } | null)
            | ({
                relationTo: 'camp-schedule-entry';
                value: string | CampScheduleEntry;
              } | null);
          url?: string | null;
          openInNewTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  socialLinks?: {
    instagram?: string | null;
    youtube?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Settings for the search engine optimization
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SEO".
 */
export interface SEO {
  id: string;
  /**
   * The title should be under 60 characters for mobile prefer 50. The title is shown in the Google search results and on desktop as the tab title. This field defines the default value for the title, but each page can have its own title.
   */
  defaultTitle: string;
  /**
   * The description should be under 155 characters for mobile prefer 105. The description is shown in the Google search results.
   */
  defaultDescription: string;
  /**
   * Keywords are not used by Google anymore, but other search engines might use them. Keywords are not shown directly to the user, but they are used by search engines to determine the content of the page. This field defines the default value for the keywords, but each page can have its own keywords.
   */
  defaultKeywords: {
    keyword: string;
    id?: string | null;
  }[];
  /**
   * The content publisher
   */
  publisher: string;
  /**
   * The HTML tag for Google Search Console verification. This tag is used to verify the ownership of the website in Google Search Console. Please paste only the content of the meta tag, not the whole meta, e.g. "gabchedl45s56dsaJKHfg_12M"
   */
  googleSearchConsoleVerification?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Settings for the Progressive Web App
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PWA".
 */
export interface PWA {
  id: string;
  /**
   * Once deployed as an PWA App to the App Store, this name will be used as the App Name. A change will require a new deployment to the App Store.
   */
  appName: string;
  /**
   * Once deployed as an PWA App to the App Store, this name will be used as the App Name. A change will require a new deployment to the App Store.
   */
  appShortName: string;
  /**
   * Once deployed as an PWA App to the App Store, this description will be used as the App Description. A change will require a new deployment to the App Store.
   */
  appDescription: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alert_settings".
 */
export interface AlertSetting {
  id: string;
  questions?:
    | {
        question: string;
        options: {
          option: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  finalResponseMessage: string;
  emergencyPhoneNumber: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  publishingStatus?: T;
  _localized_status?: T;
  _locale?: T;
  _disable_unpublishing?: T;
  mainMenu?:
    | T
    | {
        label?: T;
        linkField?:
          | T
          | {
              type?: T;
              reference?: T;
              url?: T;
              openInNewTab?: T;
            };
        subMenu?:
          | T
          | {
              label?: T;
              linkField?:
                | T
                | {
                    type?: T;
                    reference?: T;
                    url?: T;
                    openInNewTab?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  publishingStatus?: T;
  _localized_status?: T;
  _locale?: T;
  _disable_unpublishing?: T;
  minimalFooterMenu?:
    | T
    | {
        label?: T;
        linkField?:
          | T
          | {
              type?: T;
              reference?: T;
              url?: T;
              openInNewTab?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        instagram?: T;
        youtube?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SEO_select".
 */
export interface SEOSelect<T extends boolean = true> {
  defaultTitle?: T;
  defaultDescription?: T;
  defaultKeywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  publisher?: T;
  googleSearchConsoleVerification?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PWA_select".
 */
export interface PWASelect<T extends boolean = true> {
  appName?: T;
  appShortName?: T;
  appDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alert_settings_select".
 */
export interface AlertSettingsSelect<T extends boolean = true> {
  questions?:
    | T
    | {
        question?: T;
        options?:
          | T
          | {
              option?: T;
              id?: T;
            };
        id?: T;
      };
  finalResponseMessage?: T;
  emergencyPhoneNumber?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}