name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create_release_tag:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Use Node.js 24
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Load Version of Latest Release
        id: check
        uses: EndBug/version-check@v3
        with:
          file-name: ./package.json
          file-url: ::before
          static-checking: localIsNew

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.check.outputs.version }}
          release_name: Version ${{ steps.check.outputs.version }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
